import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import { Users } from "lucide-react";
import Link from 'next/link';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="flex flex-col min-h-screen h-full">
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
              <SignInButton />
              <SignUpButton />
            </SignedOut>
            <SignedIn>
              <Link href="/contacts">
                <Button size="icon">
                  <Users />
                </Button>
              </Link>
              <UserButton />
            </SignedIn>
          </header>
          <main className="flex-1">{children}</main>
          <footer className="p-4 bg-white md:p-8 lg:p-10 dark:bg-gray-800">
            <div className="mx-auto max-w-screen-xl text-center">
              <p className="my-6 text-gray-500 dark:text-gray-400">A contact management system with purpose.</p>
              <ul className="flex flex-wrap justify-center items-center mb-6 text-gray-900 dark:text-white">
                <li>
                  <a href="https://henryacastillo.com/" target="_blank" rel="noopener noreferrer" className="mr-4 hover:underline md:mr-6 ">About Henry</a>
                </li>
                <li>
                  <a href="#" className="mr-4 hover:underline md:mr-6">Contact</a>
                </li>
              </ul>
              <span className="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2025 <a href="#" className="hover:underline">Kind by Yeve</a>. All Rights Reserved.</span>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
